// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu9EWi0cEvpeIILOaF6Z1PJNLIMFijtEc',
    appId: '1:575940520069:web:792d959991f0a69754a1ec',
    messagingSenderId: '575940520069',
    projectId: 'firestore-9c237',
    authDomain: 'firestore-9c237.firebaseapp.com',
    storageBucket: 'firestore-9c237.appspot.com',
    measurementId: 'G-KVMGB9JFHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxPM3OPJaAAjmceXBMNMx7ntQmSap6Nco',
    appId: '1:575940520069:android:0979cbe2640de16054a1ec',
    messagingSenderId: '575940520069',
    projectId: 'firestore-9c237',
    storageBucket: 'firestore-9c237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDspU2_xVFRCV9JZEe0wqjt84GEXF-ZIM0',
    appId: '1:575940520069:ios:55d5a323e3442dc954a1ec',
    messagingSenderId: '575940520069',
    projectId: 'firestore-9c237',
    storageBucket: 'firestore-9c237.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDspU2_xVFRCV9JZEe0wqjt84GEXF-ZIM0',
    appId: '1:575940520069:ios:55d5a323e3442dc954a1ec',
    messagingSenderId: '575940520069',
    projectId: 'firestore-9c237',
    storageBucket: 'firestore-9c237.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu9EWi0cEvpeIILOaF6Z1PJNLIMFijtEc',
    appId: '1:575940520069:web:99f6256e409f4a6a54a1ec',
    messagingSenderId: '575940520069',
    projectId: 'firestore-9c237',
    authDomain: 'firestore-9c237.firebaseapp.com',
    storageBucket: 'firestore-9c237.appspot.com',
    measurementId: 'G-HFHC1JSWZC',
  );
}
